price_str = input("Veuillez entrer le prix des pommes: ")
print(price_str)
weight_str = input("Veuillez entrer le poids des pommes: ")
print(weight_str)
money_str = int(weight_str) * int(price_str)
print(money_str)